### ISSUE TITLE
Question: details about "suitable-methods" mode

### ISSUE THREAD

**Issue by AlleksD** [sb-ncbr/ChargeFW2#12]
Hi, Tomas 

thank you for your work. I have more a question on applicability of the methods to several relatively simple cases. 

I am trying to assign charges of [benzenethiol](https://pubchem.ncbi.nlm.nih.gov/compound/Benzenethiol) (and some other small sulfur-containing molecules). 
In my understanding, this assignment should be possible with PEOE method: at least parameters for all atoms in the molecule are present in _"PEOE_00_original.json"_ (also, the file contains parameters for S and all other atoms in correct hybridisation). However, neither method is shown in output of "suitable-methods" mode nor I can call charge-fw2 with "peoe" method directly. 

Similar question about e.g. EEM: in the case of benzenethiol it appears inappropriate, however, at least some of EEM_* files do contain sulfur with formal bonding of the 1st order. 

Is there something that I am missing in the logic of how "suitable-methods" generally works, and to which molecules I can apply charges, and to which I cannot?

Thank you,
Alex

**Comment by krab1k** [comment]
Hi Alex,

thank you for your interest in ChargeFW2.

Considering your issue. I downloaded the 3D conformer of the molecule you linked an tried "suitable-methods" and the charge calculation and it worked for me.

See:

```bash
$ ./chargefw2 --mode suitable-methods --input-file ~/Downloads/Conformer3D_CID_7969.sdf 
eem EEM_00_NEEMP_ccd2016_npa.json EEM_00_NEEMP_ccd2016_npa2.json EEM_05_NEEMP_ccd2016_mpa.json EEM_05_NEEMP_ccd2016_mpa2.json EEM_10_Cheminf_b3lyp_aim.json EEM_10_Cheminf_b3lyp_mpa.json EEM_10_Cheminf_b3lyp_npa.json EEM_10_Cheminf_hf_aim.json EEM_10_Cheminf_hf_mpa.json EEM_10_Cheminf_hf_npa.json EEM_40_Svob2007_cbeg2.json EEM_40_Svob2007_chal2.json EEM_40_Svob2007_cmet2.json EEM_40_Svob2007_hm2.json EEM_60_Ionescu2013_npa_gas.json EEM_60_Ionescu2013_npa_pcm.json EEM_65_Ionescu2013_mpa_gas.json EEM_65_Ionescu2013_mpa_pcm.json
qeq QEq_00_original.json
eqeq
peoe PEOE_00_original.json
mpeoe MPEOE_00_original.json
gdac GDAC_00_original.json
sqe SQE_10_Schindler2021_CCD_gen.json SQE_20_Schindler2021_DTP_small.json
sqeq0 SQEq0_10_Schindler2021_CCD_gen.json SQEq0_20_Schindler2021_DTP_small.json
sqeqp SQEqp_10_Schindler2021_CCD_gen.json SQEqp_20_Schindler2021_DTP_small.json
mgc
kcm KCM_00_original.json
denr DENR_00_from_QEq.json
tsef TSEF_00_from_QEq.json
veem
formal
sqe SQE_10_Schindler2021_CCD_gen.json SQE_20_Schindler2021_DTP_small.json
sqeqp SQEqp_10_Schindler2021_CCD_gen.json SQEqp_20_Schindler2021_DTP_small.json

$ ./chargefw2 --mode charges --method peoe  --input-file ~/Downloads/Conformer3D_CID_7969.sdf --chg-out-dir /tmp
Method: PEOE
Best parameters found: PEOE_00_original.json
Parameters: Gasteiger 1980
Common parameters
dampH: 20.020
Atom parameters
H  hbo    1   :  7.170  6.240 -0.560 
C  hbo    1   :  7.980  9.180  1.880 
C  hbo    2   :  8.790  9.320  1.510 
C  hbo    3   : 10.390  9.450  0.730 
N  hbo    1   : 11.540 10.820  1.360 
N  hbo    2   : 12.870 11.150  0.850 
N  hbo    3   : 15.680 11.700 -0.270 
O  hbo    1   : 14.180 12.920  1.390 
O  hbo    2   : 17.070 13.790  0.470 
F  hbo    1   : 14.660 13.850  2.310 
Cl hbo    1   : 11.000  9.690  1.350 
Br hbo    1   : 10.080  8.470  1.160 
I  hbo    1   :  9.900  7.960  0.960 
S  hbo    1   : 10.140  9.130  1.380 

Number of unclassified molecules: 0

Number of molecules: 1
Number of atoms: 13
H  hbo    1   : 6
C  hbo    2   : 6
S  hbo    1   : 1

$ cat /tmp/Conformer3D_CID_7969.sdf.txt 
7969
-0.14261 0.00474 -0.04856 -0.04856 -0.06073 -0.06073 -0.06169 0.06284 0.06284 0.06179 0.06179 0.06176 0.10711
```

Do you use the same input file? And do you have ChargeFW2 installed and not just compiled? The paths for the data files (e.g., parameter sets) are set during the compilation with respect to the "CMAKE_INSTALL_PREFIX".

Best,
Tomáš

**Comment by AlleksD** [comment]
Hi, Tomáš

thank you for the detailed replay and for the demo.

Yes, I've repeated your path, and all works as you described. 
As for my configuration I use Docker setup (I had some issues installing dependencies on Ubuntu 18.04 and openSUSE 15.3, but in Docker everything works smooth)

So, my problem was that I used .pdb files. Seems the chargefw2 generally understands them but in a different way. Please see the shell output from the program for the same benzenethiol molecule in .sdf and .pdb formats (I also attach [both files](https://drive.google.com/drive/folders/15cFffvvU7DxFd9jmUnjm3YGuS0jg9m6a?usp=sharing)). 

```
$ >> ls -lu
total 236
-rw-r--r-- 1 root root   88647 Feb 10 11:15 ChargesDemo.ipynb
-rw-r--r-- 1 root root    1366 Feb 10 10:44 molecule.pdb
-rw-r--r-- 1 1000 users   1272 Feb 10 11:24 molecule.sdf
-rwxrwxrwx 1 1000 users 100646 Feb  7 12:57 omim_1-10.lmps
-rw-r--r-- 1 root root   19856 Feb  7 12:57 omim_1-10.pdb

$ >> chargefw2 --mode suitable-methods --input-file molecule.pdb
qeq QEq_00_original.json
eqeq
mgc
denr DENR_00_from_QEq.json
tsef TSEF_00_from_QEq.json
veem
formal

$ >> chargefw2 --mode suitable-methods --input-file molecule.sdf
eem EEM_00_NEEMP_ccd2016_npa.json EEM_00_NEEMP_ccd2016_npa2.json EEM_05_NEEMP_ccd2016_mpa.json EEM_05_NEEMP_ccd2016_mpa2.json EEM_10_Cheminf_b3lyp_aim.json EEM_10_Cheminf_b3lyp_mpa.json EEM_10_Cheminf_b3lyp_npa.json EEM_10_Cheminf_hf_aim.json EEM_10_Cheminf_hf_mpa.json EEM_10_Cheminf_hf_npa.json EEM_40_Svob2007_cbeg2.json EEM_40_Svob2007_chal2.json EEM_40_Svob2007_cmet2.json EEM_40_Svob2007_hm2.json EEM_60_Ionescu2013_npa_gas.json EEM_60_Ionescu2013_npa_pcm.json EEM_65_Ionescu2013_mpa_gas.json EEM_65_Ionescu2013_mpa_pcm.json
qeq QEq_00_original.json
eqeq
peoe PEOE_00_original.json
mpeoe MPEOE_00_original.json
gdac GDAC_00_original.json
sqe SQE_10_Schindler2021_CCD_gen.json SQE_20_Schindler2021_DTP_small.json
sqeq0 SQEq0_10_Schindler2021_CCD_gen.json SQEq0_20_Schindler2021_DTP_small.json
sqeqp SQEqp_10_Schindler2021_CCD_gen.json SQEqp_20_Schindler2021_DTP_small.json
mgc
kcm KCM_00_original.json
denr DENR_00_from_QEq.json
tsef TSEF_00_from_QEq.json
veem
formal
```

And, generally speaking, both files contain the same amount of information: coordinates, element names, and connectivities (I have edited .sdf file  on purpose deleting all info starting from PubChem CID).

Maybe my .pdf file is not formatted correctly. 

Thank you for your help!
Alex

**Comment by krab1k** [comment]
Hi Alex,

I'm glad that it works for you now! :-) As for the reading of PDB files (and mmCIFs) within ChargeFW2, let me explain how that works.

First of all, PDB files were meant to store proteins or peptides and therefore they do not contain information about bonds, with an exception of CONECT records for non-standard residues and two [others](https://www.wwpdb.org/documentation/file-format-content/format33/sect10.html). However, as there is no way of setting the order of the bond, we do not use these records.

As for your PDB file, the residue is identified as [RES](https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/RES) (the fourth column of a PDB file) and the bonding information is added according to this [information](https://www.ebi.ac.uk/pdbe-srv/pdbechem/bond/list/RES) based on the naming of the atoms. This nomenclature is standard for a given residue so there is no ambiguity.

Benzenethiol is actually one of the standard [residues](https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/BT6), so if you use the correct PDB file, the calculation of charges should proceed as expected.

However, I would recommend using SDF files for small organic molecules as they contain explicit information about the bonding (including orders).

Best,
Tomáš
