### ISSUE TITLE
Uploading a bundle of zipped mol2 files 

### ISSUE THREAD

**Issue by andro-demir** [sb-ncbr/ChargeFW2#13]
Hi,

I have a large dataset with thousands of mol2 files. I can get the partial charges when I upload them one-by-one, but if I upload the zipped folder on the website, I receive this error: "Invalid file provided. Supported types are common chemical formats: sdf, mol2, pdb, cif and zip or tar.gz of those." What should I do? Thanks

**Comment by krab1k** [comment]
Replied by email, no response. Closing.
