### ISSUE TITLE
Installation issues for .ipynb

### ISSUE THREAD

**Issue by RafiBrent** [sb-ncbr/ChargeFW2#15]
Thanks so much for creating this tool! I'd like to be able to integrate it into a broader pipeline that I've been working with in Google Colab. However, I've had some issues with the installation-- specifically, the cmake commands execute successfully but I'm unable to find a .../lib folder for setting the python pointer as described in the documentation. This is my first time using cmake, so any advice would be greatly appreciated!

**Comment by krab1k** [comment]
Hi, sorry for the late response and thanks for your interest in ChargeFW2. I don't have experience with Google Colab, but I can at least provide some general comments.

After the installation (https://github.com/sb-ncbr/ChargeFW2#installation), there should be a file named like `chargefw2_python.cpython-310-x86_64-linux-gnu.so` in `<WHERE-TO-INSTALL>/lib` directory.

If you don't provide the `-DCMAKE_INSTALL_PREFIX` to `cmake`, it defaults to `/usr/local` (at least on my linux system). So assuming this, you need to tell the Python to look at that directory by setting the PYTHONPATH variable:

```bash
$ PYTHONPATH=/usr/local/lib python -c "import chargefw2_python; print(chargefw2_python.__file__)"
/usr/local/lib/chargefw2_python.cpython-310-x86_64-linux-gnu.so
```

or alternatively by extending `sys.path` list:

```bash
$  python -c "import sys; sys.path.append('/usr/local/lib'); import chargefw2_python; print(chargefw2_python.__file__)"
/usr/local/lib/chargefw2_python.cpython-310-x86_64-linux-gnu.so
```

BTW: You might want to consider using our experimental API (http://78.128.250.156/) for ChargeFW2. It's a work in progress right now, but it might be useful to you as well. Tagging @LenkaPt, as she is responsible for it.

**Comment by LenkaPt** [comment]
Hi, thank you for using our API! 
I am sorry, there was a bug in get_suitable_method, but it should work now.
Regarding your question about replicating the automatic method selection - the suitable methods function does return multiple methods, but they are ordered from the most suitable one (the first one in the response) to the least one. You can also get multiple suitable parameters for a particular method - they are sorted as well from the most suitable.

I am currently working on improving the calculate_charges method. I would like to implement the automatic selection as well as ACC II has. If the user does not specify a method for calculation, API will select the most suitable one. I am hoping to have it done within the day. 
Sorry for the inconvenience and thank you for reporting the bug!

**Comment by RafiBrent** [comment]
Perfect, thanks so much! Looks like the fix was successful, and thanks so much for implementing the automatic method & parameter selection as part of calculate_charges. Best of luck with the rest of the project!
